id: P3C2A2D2F
initial_creation_type: ocr
source_metadata:
  volumes:
    9023e465f5a94688af95bab97f642304:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: གསུམ་ལ་སྐབས་སུ་འགྲོ་བ་བདུན་ཅུ་པ།
      total_pages: 1498
      volume_number: 65
