id: DE93F9149
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-06T09:37:06+00:00'
last_modified: '2022-05-27T15:45:49.270902+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    2be8:
      image_group_id: I1PD95910
      title: གསུམ་ལ་སྐབས་སུ་འགྲོ་བ་བདུན་ཅུ་པ།
      total_pages: 1498
      order: 65
      base_file: 2be8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
